apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: georgevazj/hello-gitops
  newTag: 4c17fcff0ef6230eace0aaac34d43929a8fb0c6f
